env: staging
db_user: ershadul
db_password: "*****"
db_name: alkawsar_v2
db_host: localhost
app_name: "alkawsar-{{ env }}"
python_version: python3
virtualenv_python: python3
git_repo: git@github.com:ershadul/alkawsarcms.git
git_branch: staging
virtualenv_path:  "/home/{{ system_user }}/env"
app_path: "/home/{{ system_user }}/{{ app_name }}"
django_manage_path: "{{ app_path }}"
wsgi_module: alkawsarcms.wsgi:application
ssl_cert_domain: staging.alkawsar.com
ansible_user: ubuntu
ansible_python_interpreter: /usr/bin/python3
ansible_ssh_private_key_file: ~/.ssh/aws-lightsail-ap-southeast-1.pem
