---
- hosts: production
  become: yes
  roles:
    - { role: users, tags: users }
    - { role: common, tags: common }
    # - { role: database, tags: database }
    - { role: elasticsearch, tags: elasticsearch }
    - { role: application, tags: application }
    - { role: webserver, tags: webserver }
