---
- name: Install MySQL packages
  apt: pkg={{item}} state=present
  with_items:
    - bundler
    - libmysqlclient-dev
    - mysql-server
    - mysql-client
    - python3-mysqldb

- name: Install mysqlclient using pip
  pip: name={{ item }} state=present executable=pip3
  with_items:
    - mysqlclient

- name: Remove the MySQL test database
  mysql_db: name=test state=absent

- name: Create databases
  mysql_db:
    name: "{{ db_name }}"
    state: present
    collation: utf8_general_ci
    encoding: utf8

- name: Add DB user and allow access to alkawsar_v2 only
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}" 
    host: localhost
    priv: "{{ db_name }}.*:ALL"
    state: present

- name: Create local my.cnf for root user
  template:
    src: my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600

- name: Restart the MySQL service
  service: name=mysql state=restarted enabled=true
