---
- name: build-essential
  apt:
    name: build-essential
    state: present
    update_cache: yes

- name: download latest stable redis
  get_url: url=http://download.redis.io/redis-stable.tar.gz dest=/tmp/redis-stable.tar.gz

- name: untar redis
  unarchive: src=/tmp/redis-stable.tar.gz dest=/tmp copy=no

- name: build redis
  shell: cd /tmp/redis-stable && make

- name: copy redis-cli to /usr/local/bin
  shell: cp /tmp/redis-stable/src/redis-cli /usr/local/bin/ && sudo chmod 755 /usr/local/bin/redis-cli
