---
- name: Apt cache update
  apt: update_cache=yes

- name: Install packages
  apt: name={{ item }} state=present
  with_items:
    - locales
    - build-essential    
    - "{{ python_version + '-dev' }}"
    - "{{ python_version + '-pip' }}"
    - python3-dev
    - python3-pip
    - git-core
    - curl
    - gcc
    - make
    - vim
    - nano
    - bundler
    - htop
    - gettext
    - libffi-dev
    - software-properties-common

